name: check
on: [ push, pull_request ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: detekt
        run: |
          ./gradlew detektAll
      - name: ktlint
        run: |
          ./gradlew ktlintCheck
      - name: lint
        run: |
          ./gradlew lint
  build:
    runs-on: macos-latest
    needs: check
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: build
        run: |
          ./gradlew :app:assembleDebug :app:desktopJar :app:jsJar :app:compileKotlinUikitX64 :app:compileKotlinUikitArm64
